### ISSUE TITLE
docker-compose: apt-utils has no installation candidate

### ISSUE THREAD

**Issue by reavessm** [pixelfed/pixelfed#2108]
ran `docker-compose up` and got the following error:

db uses an image, skipping
redis uses an image, skipping
Building app
Step 1/11 : FROM php:7.4-apache-buster
 ---> 5e1d7ed3b92a
Step 2/11 : ARG COMPOSER_VERSION="1.9.1"
 ---> Using cache
 ---> cd4561f3a324
Step 3/11 : ARG COMPOSER_CHECKSUM="1f210b9037fcf82670d75892dfc44400f13fe9ada7af9e787f93e50e3b764111"
 ---> Using cache
 ---> d6a513b35eb8
Step 4/11 : RUN apt-get update  && apt-get install -y --no-install-recommends apt-utils  && apt-get install -y --no-install-recommends git gosu ffmpeg       optipng pngquant jpegoptim gifsicle libpq-dev libsqlite3-dev locales zip unzip libzip-dev libcurl4-openssl-dev       libfreetype6 libicu-dev libjpeg62-turbo libpng16-16 libxpm4 libwebp6 libmagickwand-6.q16-6       libfreetype6-dev libjpeg62-turbo-dev libpng-dev libxpm-dev libwebp-dev libmagickwand-dev mariadb-client && sed -i '/en_US/s/^#//g' /etc/locale.gen  && locale-gen && update-locale  && docker-php-source extract  && docker-php-ext-configure gd       --with-freetype       --with-jpeg       --with-webp       --with-xpm  && docker-php-ext-install pdo_mysql pdo_pgsql pdo_sqlite pcntl gd exif bcmath intl zip curl  && docker-php-ext-enable pcntl gd exif zip curl  && a2enmod rewrite remoteip  && {     echo RemoteIPHeader X-Real-IP ;     echo RemoteIPTrustedProxy 10.0.0.0/8 ;     echo RemoteIPTrustedProxy 172.16.0.0/12 ;     echo RemoteIPTrustedProxy 192.168.0.0/16 ;     echo SetEnvIf X-Forwarded-Proto "https" HTTPS=on ;    } > /etc/apache2/conf-available/remoteip.conf  && a2enconf remoteip  && curl -LsS https://getcomposer.org/download/${COMPOSER_VERSION}/composer.phar -o /usr/bin/composer  && echo "${COMPOSER_CHECKSUM}  /usr/bin/composer" | sha256sum -c -  && chmod 755 /usr/bin/composer  && apt-get autoremove --purge -y        libfreetype6-dev libjpeg62-turbo-dev libpng-dev libxpm-dev libvpx-dev libmagickwand-dev  && rm -rf /var/cache/apt  && docker-php-source delete
 ---> Running in 27292acbe7fd
**Err:1 http://deb.debian.org/debian buster InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://security.debian.org/debian-security buster/updates InRelease
  Temporary failure resolving 'security.debian.org'
Err:3 http://deb.debian.org/debian buster-updates InRelease
  Temporary failure resolving 'deb.debian.org'**
Reading package lists...
**W: Failed to fetch http://deb.debian.org/debian/dists/buster/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/debian-security/dists/buster/updates/InRelease  Temporary failure resolving 'security.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/buster-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.**
Reading package lists...
Building dependency tree...
Reading state information...
Package apt-utils is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  apt

E: Package 'apt-utils' has no installation candidate
Service 'app' failed to build: The command '/bin/sh -c apt-get update  && apt-get install -y --no-install-recommends apt-utils  && apt-get install -y --no-install-recommends git gosu ffmpeg       optipng pngquant jpegoptim gifsicle libpq-dev libsqlite3-dev locales zip unzip libzip-dev libcurl4-openssl-dev       libfreetype6 libicu-dev libjpeg62-turbo libpng16-16 libxpm4 libwebp6 libmagickwand-6.q16-6       libfreetype6-dev libjpeg62-turbo-dev libpng-dev libxpm-dev libwebp-dev libmagickwand-dev mariadb-client && sed -i '/en_US/s/^#//g' /etc/locale.gen  && locale-gen && update-locale  && docker-php-source extract  && docker-php-ext-configure gd       --with-freetype       --with-jpeg       --with-webp       --with-xpm  && docker-php-ext-install pdo_mysql pdo_pgsql pdo_sqlite pcntl gd exif bcmath intl zip curl  && docker-php-ext-enable pcntl gd exif zip curl  && a2enmod rewrite remoteip  && {     echo RemoteIPHeader X-Real-IP ;     echo RemoteIPTrustedProxy 10.0.0.0/8 ;     echo RemoteIPTrustedProxy 172.16.0.0/12 ;     echo RemoteIPTrustedProxy 192.168.0.0/16 ;     echo SetEnvIf X-Forwarded-Proto "https" HTTPS=on ;    } > /etc/apache2/conf-available/remoteip.conf  && a2enconf remoteip  && curl -LsS https://getcomposer.org/download/${COMPOSER_VERSION}/composer.phar -o /usr/bin/composer  && echo "${COMPOSER_CHECKSUM}  /usr/bin/composer" | sha256sum -c -  && chmod 755 /usr/bin/composer  && apt-get autoremove --purge -y        libfreetype6-dev libjpeg62-turbo-dev libpng-dev libxpm-dev libvpx-dev libmagickwand-dev  && rm -rf /var/cache/apt  && docker-php-source delete' returned a non-zero code: 100

Also tried with php:7.4.4-apache-buster and got the same error.  Trying to follow [these instructions](https://jonnev.se/pixelfed-beta-with-docker-and-traefik/), minus traefik.

Seems to be related to [this issue](https://github.com/docker-library/php/issues/812), but changing the network to host in the `docker-compose.yml` doesn't seem to fix it.

Relevant `docker-compose.yml`

```yaml
---
version: '3'

# In order to set configuration, please use a .env file in
# your compose project directory (the same directory as your
# docker-compose.yml), and set database options, application
# name, key, and other settings there.
# A list of available settings is available in .env.example
#
# The services should scale properly across a swarm cluster
# if the volumes are properly shared between cluster members.

services:

  app:
    # Comment to use dockerhub image
    build:
      context: .
      dockerfile: contrib/docker/Dockerfile.apache
      #dockerfile: contrib/docker/Dockerfile.fpm
    image: pixelfed
    restart: unless-stopped
    ## If you have a traefik running, uncomment this to expose Pixelfed
    # labels:
    #   - traefik.enable=true
    #   - traefik.frontend.rule=Host:your.url
    #   - traefik.port=80
    ## If you have a standard reverse proxy, uncommit this to expose Pixelfed
    # ports:
    #   - "127.0.0.1:8080:80"
    env_file:
      - ./.env
    volumes:
      - "app-storage:/var/www/storage"
      - "app-bootstrap:/var/www/bootstrap"
      - "./.env:/var/www/.env"
    networks:
      - host
      - internal
        #- external

  worker:  # Comment this whole block if HORIZON_EMBED is true.
    # Comment to use dockerhub image
    build:
      context: .
      dockerfile: contrib/docker/Dockerfile.apache
      #dockerfile: contrib/docker/Dockerfile.fpm
    image: pixelfed
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - "app-storage:/var/www/storage"
      - "app-bootstrap:/var/www/bootstrap"
    networks:
      - host  # Required for ActivityPub
      - internal
        #- external  # Required for ActivityPub
    command: gosu www-data php artisan horizon
    
  db:
    image: mysql:8.0
    restart: unless-stopped
    networks:
      - internal
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=pixelfed
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - "db-data:/var/lib/mysql"

  redis:
    image: redis:5-alpine
    restart: unless-stopped
    volumes:
      - "redis-data:/data"
    networks:
      - internal

# Adjust your volume data in order to store data where you wish
volumes:
  redis-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/PixelFed/redis-data'
  db-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/PixelFed/db-data'
  app-storage:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/PixelFed/app-data'
  app-bootstrap:  
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/PixelFed/app-bootstrap'

networks:
  internal:
    internal: true
  host:
    driver: host
  #external:
    #driver: bridge
```

Got the same errors with host and external networks.
