### ISSUE TITLE
Improve the dark color scheme to something more smooth and still be as accessible as possible

### ISSUE THREAD

**Issue by brunomiguel** [pixelfed/pixelfed#5089]
Some users, myself included, get eye strain from full black backgrounds. Pixelfed uses full black for the website background, and Android app too, so it can be less than ideal for some users. To tackle this, I've been using a userstyle on my desktop browser, but I'm sharing the changes I did here, so it can be at least evaluated for changes in the [dark theme palette](https://github.com/pixelfed/pixelfed/blob/f91119c564ae6ab7f8604495fdb8dd003aca3cb4/resources/assets/sass/spa.scss#L29) and become a starting point for this change.

```css
@media (prefers-color-scheme: dark) {
    :root {
        --light: #181d25 !important;
        --dark: #EFEDE7 !important;
        --body-bg: #181d25 !important;
        --body-color: #fdfdfb !important;
        --nav-bg: #181d25 !important;
        --bg-light: #181d25 !important;

        --light-gray: #2a2b37 !important;
        --text-lighter: #818181 !important;

        --card-bg: #2e3544 !important;
        --light-hover-bg: #181d25 !important;
        --btn-light-border: #718086 !important;
        --input-border: #161618 !important;
        --comment-bg: #181d25 !important;
        --border-color: #818181 !important;
        --card-header-accent: #181d25 !important;

        --dropdown-item-hover-bg: #1E252F !important;
        --dropdown-item-hover-color: #818181 !important;
        --dropdown-item-color: #64748b !important;
        --dropdown-item-active-color: #EFEDE7 !important;
        
        --link-color: #f5f9b0 !important;
    }

    a {
        color: var(--link-color) !important;
    }
}
```

I leave an image showcasing the colors (with a different typeface, because reasons ^^')
![image](https://github.com/pixelfed/pixelfed/assets/1161202/806db6e7-4574-4f89-a2c2-05d8575f54f7)
